version: '3.3'
services:
    postgres:
        image: postgres:13-alpine
        volumes:
            - /var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=pgpassword
        networks:
            backend:
                aliases:
                  - postgres

    flask:
        build: ./app_srv/.
        image: post-check_app:latest
        depends_on:
            - postgres
        networks:
            backend:
                aliases:
                  - flask

    nginx:
        build: ./nginx/.
        image: post_nginx
        depends_on:
            - flask
        ports:
            - 8080:8080
        networks:
            backend:
                aliases:
                  - nginx
            frontend:
                aliases: 
                  - nginx
networks:
    frontend:
    backend:  